# Generated by Django 4.0.2 on 2022-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_date', models.DateField()),
                ('blog_text', models.TextField(max_length=300)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
